#!/bin/bash

set -e

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

link_security_config() {
    local source="$1"
    local target="$2"

    if [ -L "$target" ] && [ "$(readlink "$target")" = "$source" ]; then
        return
    fi

    if [ -e "$target" ] || [ -L "$target" ]; then
        local backup="${target}.backup.$(date +%Y%m%d%H%M%S)"
        local counter=1
        while [ -e "$backup" ] || [ -L "$backup" ]; do
            backup="${target}.backup.$(date +%Y%m%d%H%M%S).$counter"
            counter=$((counter + 1))
        done
        echo "Warning: backing up existing $target to $backup before linking security config."
        mv "$target" "$backup"
    fi

    ln -sf "$source" "$target"
}

# Generate machine-specific Hyprland GPU selection (config/hypr/gpu.conf).
# Picks the GPU that owns a connected display as primary so the compositor
# never depends on a cold/uninitialized secondary GPU (the NVIDIA cold-boot
# kick-out). Single-GPU machines get a comment-only file (aquamarine
# auto-selects the only card). gpu.conf is gitignored.
generate_hypr_gpu_conf() {
    local gpu_conf="$DOTFILES/config/hypr/gpu.conf"

    # Collect render GPUs (DRM cards backed by a kernel driver).
    local gpus=() c
    for c in /sys/class/drm/card[0-9] /sys/class/drm/card[0-9][0-9]; do
        [ -e "$c/device/driver" ] && gpus+=("$c")
    done

    if [ "${#gpus[@]}" -le 1 ]; then
        cat > "$gpu_conf" <<'EOF'
# Auto-generated by symlink_arch.sh — single GPU detected.
# aquamarine auto-selects the only card; no AQ_DRM_DEVICES needed.
EOF
        echo "Hyprland GPU: single GPU, no AQ_DRM_DEVICES needed."
        return
    fi

    # Resolve a DRM card to its /dev/dri/cardN node. AQ_DRM_DEVICES is
    # colon-separated, so by-path names (which contain ':' in the PCI address)
    # cannot be used here — only the colon-free cardN nodes work.
    devnode_for() {
        echo "/dev/dri/$(basename "$1")"
    }

    # Primary = first GPU with a connected display connector; rest follow.
    local primary="" others=() conn
    for c in "${gpus[@]}"; do
        local connected=0
        for conn in "$c"/card*-*/status; do
            [ -f "$conn" ] && [ "$(cat "$conn")" = "connected" ] && { connected=1; break; }
        done
        if [ -z "$primary" ] && [ "$connected" = 1 ]; then
            primary="$c"
        else
            others+=("$c")
        fi
    done
    if [ -z "$primary" ]; then
        primary="${gpus[0]}"
        others=("${gpus[@]:1}")
    fi

    local devs o
    devs="$(devnode_for "$primary")"
    for o in "${others[@]}"; do
        devs="${devs}:$(devnode_for "$o")"
    done

    cat > "$gpu_conf" <<EOF
# Auto-generated by symlink_arch.sh — machine-specific, do not commit.
# Primary render GPU listed first: it owns a connected display and is ready at
# cold boot. Any secondary GPU follows and stays available for render-offload.
env = AQ_DRM_DEVICES,${devs}
EOF
    echo "Hyprland GPU: AQ_DRM_DEVICES=${devs}"
}

# Ensure .config exists
mkdir -p "$HOME/.config"

# Root setup
echo "[ -f ~/.profile ] && source ~/.profile" | sudo tee -a /root/.bashrc > /dev/null
sudo ln -sf "$DOTFILES/root_profile" /root/.profile
sudo mkdir -p /root/.config
sudo ln -sfT "$DOTFILES/nvim" /root/.config/nvim

# User directories
ln -sfT "$DOTFILES/nvim" "$HOME/.config/nvim"

# User directories
ln -sfT "$DOTFILES/config/hypr" "$HOME/.config/hypr"
ln -sfT "$DOTFILES/config/kitty" "$HOME/.config/kitty"
ln -sfT "$DOTFILES/config/waybar" "$HOME/.config/waybar"
ln -sfT "$DOTFILES/config/gtk-3.0" "$HOME/.config/gtk-3.0"
ln -sfT "$DOTFILES/config/gtk-4.0" "$HOME/.config/gtk-4.0"
ln -sfT "$DOTFILES/config/wofi" "$HOME/.config/wofi"
ln -sfT "$DOTFILES/config/mako" "$HOME/.config/mako"
mkdir -p "$HOME/.config/audacious"
ln -sf "$DOTFILES/config/audacious/config" "$HOME/.config/audacious/config"

# User applications (desktop entries)
mkdir -p "$HOME/.local/share/applications"
ln -sf "$DOTFILES/config/applications/google-chrome.desktop" "$HOME/.local/share/applications/google-chrome.desktop"

# User bin scripts
mkdir -p "$HOME/.local/bin"
ln -sf "$DOTFILES/bin/less" "$HOME/.local/bin/less"
ln -sf "$DOTFILES/bin/capture" "$HOME/.local/bin/capture"
ln -sf "$DOTFILES/bin/battery-monitor" "$HOME/.local/bin/battery-monitor"
ln -sf "$DOTFILES/bin/launch-waybar" "$HOME/.local/bin/launch-waybar"
ln -sf "$DOTFILES/bin/caffeine" "$HOME/.local/bin/caffeine"
ln -sf "$DOTFILES/bin/powermenu" "$HOME/.local/bin/powermenu"

# User files
ln -sf "$DOTFILES/gitconfig" "$HOME/.gitconfig"
ln -sf "$DOTFILES/gitignore" "$HOME/.gitignore"
ln -sf "$DOTFILES/profile" "$HOME/.profile"
ln -sf "$DOTFILES/tern-project" "$HOME/.tern-project"
ln -sf "$DOTFILES/editorconfig" "$HOME/.editorconfig"
link_security_config "$DOTFILES/security/npmrc.conf" "$HOME/.npmrc"
link_security_config "$DOTFILES/security/bunfig.toml" "$HOME/.bunfig.toml"
link_security_config "$DOTFILES/security/yarnrc.yml" "$HOME/.yarnrc.yml"
ln -sf "$DOTFILES/make-completion.bash" "$HOME/.make-completion.bash"
ln -sf "$DOTFILES/tmux.conf" "$HOME/.tmux.conf"

mkdir -p "$HOME/.config/pnpm" "$HOME/.config/renovate"
link_security_config "$DOTFILES/security/pnpm.yaml" "$HOME/.config/pnpm/config.yaml"
link_security_config "$DOTFILES/security/renovate.json" "$HOME/.config/renovate/config.json"

# Claude Code
mkdir -p "$HOME/.claude"
ln -sf "$DOTFILES/claude/statusline-command.sh" "$HOME/.claude/statusline-command.sh"

# Copy user-specific config only if it doesn't exist
[[ -f "$HOME/.gitconfig-user" ]] || cp "$DOTFILES/gitconfig-user" "$HOME/.gitconfig-user"

# Generate machine-specific Hyprland GPU selection before any reload
generate_hypr_gpu_conf

# Reload Hyprland config (only if a Hyprland session is running)
if command -v hyprctl &> /dev/null && [ -n "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
    hyprctl reload
fi

echo "Dotfiles linked."
