theme = "moonfly"
hide-mouse-cursor-when-typing = true

[fonts]
family = "Ubuntu Mono"
size = 16

[editor]
program = "nvim"
args = []

[renderer]
strategy = "game"
backend = "Vulkan"
# filters = ["newpixiecrt"]
